/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stadium.glb -Tt 
Files: stadium.glb [21.97MB] > C:\Users\immam\dev\projects\football-match-viewer\public\models\stadium-transformed.glb [975.09KB] (96%)
*/

import { useGLTF } from "@react-three/drei";
import { useEffect } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

const MODEL_URL = "models/stadium-transformed.glb";

type GLTFResult = GLTF & {
  nodes: {
    standsN: THREE.Mesh;
    EnterStairs: THREE.Mesh;
    EnterRoof: THREE.Mesh;
    Pitch: THREE.Mesh;
    bannerETop: THREE.Mesh;
    GoalFrameWest: THREE.Mesh;
    bannerNPitch: THREE.Mesh;
    bannerWPitch: THREE.Mesh;
  };
  materials: {
    Material_Standings: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    Material_Bench: THREE.MeshStandardMaterial;
    Material_Pitch_002: THREE.MeshStandardMaterial;
    Material_Banner_Top: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    Material_Ads: THREE.MeshStandardMaterial;
  };
};

export function Stadium(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(MODEL_URL) as GLTFResult;
  useEffect(() => {
    if (materials.Material_Standings.map) {
      materials.Material_Standings.map.repeat = new THREE.Vector2(2, 3.8);
      materials.Material_Standings.side = 0;
      materials.Material_Pitch_002.side = 0;
      materials.Material_Pitch_002.roughness = 0.8;
      materials.Material_Pitch_002.metalness = 0.1;
      materials.PaletteMaterial001.side = 0;
      // materials.PaletteMaterial002.side = 0;
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.standsN.geometry}
        material={materials.Material_Standings}
      />
      <mesh
        geometry={nodes.EnterStairs.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.EnterRoof.geometry}
        material={materials.Material_Bench}
      />
      <mesh
        geometry={nodes.Pitch.geometry}
        material={materials.Material_Pitch_002}
      />
      <mesh
        geometry={nodes.bannerETop.geometry}
        material={materials.Material_Banner_Top}
      />
      <mesh
        geometry={nodes.GoalFrameWest.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.bannerNPitch.geometry}
        material={materials.Material_Ads}
      />
      <mesh
        geometry={nodes.bannerWPitch.geometry}
        material={materials.Material_Ads}
      />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
