/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 player.glb -Tt -R 512 
Files: player.glb [17.24MB] > C:\Users\immam\dev\projects\football-match-viewer\public\models\player-transformed.glb [2.51MB] (85%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'sk.jog_forward' | 'sk.soccer_idle' | 'sk.offensive_idle.anim' | 'sk.idle.anim' | 'sk.walking.anim' | 'pl.t_pose' | 'sk.soccer_pass.anim' | 'sk.soccer_header.anim' | 'sk.throw_in.anim' | 'sk.strike_forward_jog.anim' | 'sk.jog_backward.anim' | 'sk.left_turn.anim' | 'sk.right_turn.anim' | 'sk.jog_strafe_left.anim' | 'sk.jog_strafe_right.anim' | 'sk.walking_backward.anim'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Ch38_Body: THREE.SkinnedMesh
    Ch38_Hair: THREE.SkinnedMesh
    Ch38_Shirt: THREE.SkinnedMesh
    Ch38_Shoes: THREE.SkinnedMesh
    Ch38_Shorts: THREE.SkinnedMesh
    Ch38_Socks: THREE.SkinnedMesh
    mixamorig5Hips: THREE.Bone
  }
  materials: {
    Body_Material: THREE.MeshStandardMaterial
    Ch38_hair: THREE.MeshStandardMaterial
    Shirt_Material: THREE.MeshStandardMaterial
    Shoes_Material: THREE.MeshStandardMaterial
    Shorts_Material: THREE.MeshStandardMaterial
    Socks_Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/player-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Player" scale={0.01}>
          <primitive object={nodes.mixamorig5Hips} />
        </group>
        <skinnedMesh name="Ch38_Body" geometry={nodes.Ch38_Body.geometry} material={materials.Body_Material} skeleton={nodes.Ch38_Body.skeleton} scale={0.01} />
        <skinnedMesh name="Ch38_Hair" geometry={nodes.Ch38_Hair.geometry} material={materials.Ch38_hair} skeleton={nodes.Ch38_Hair.skeleton} scale={0.01} />
        <skinnedMesh name="Ch38_Shirt" geometry={nodes.Ch38_Shirt.geometry} material={materials.Shirt_Material} skeleton={nodes.Ch38_Shirt.skeleton} scale={0.01} />
        <skinnedMesh name="Ch38_Shoes" geometry={nodes.Ch38_Shoes.geometry} material={materials.Shoes_Material} skeleton={nodes.Ch38_Shoes.skeleton} scale={0.01} />
        <skinnedMesh name="Ch38_Shorts" geometry={nodes.Ch38_Shorts.geometry} material={materials.Shorts_Material} skeleton={nodes.Ch38_Shorts.skeleton} scale={0.01} />
        <skinnedMesh name="Ch38_Socks" geometry={nodes.Ch38_Socks.geometry} material={materials.Socks_Material} skeleton={nodes.Ch38_Socks.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/player-transformed.glb')
